#!/bin/sh

EMACS=/usr/bin/emacs
EMACS_CLIENT=/usr/bin/emacsclient
SERVER_RUNNING=`ps -ef | grep $USER | grep "emacs --daemon" | grep -v grep`

if [ -z "$SERVER_RUNNING" ]; then
	$EMACS --daemon
fi

FRAMES_OPEN=`$EMACS_CLIENT --no-wait --eval '(length (frame-list))'`
if [ 1 -eq $FRAMES_OPEN ]; then
	$EMACS_CLIENT --no-wait --create-frame $@
	$EMACS_CLIENT --no-wait --eval '(set-frame-size (selected-frame) 80 35)'
else
    	$EMACS_CLIENT --no-wait --reuse-frame $@
fi
